Update muelu-cheby2er12-drop0.02-smoo-rebaltarg10k-explR-rebalPR-aggs…
Exawind/solver-performance pull request #4
Opened 2019-02-09 16:43 UTC by sthomas61

Reducing the number of AMG V-cycle pre-smooth sweeps leads to 50% drop in solver time
and a 10-20% reduction in model run time. Tests to date on ABL and NREL 5WM G1 with
Chebyshev smoother and Trilinos solver stack (on eagle and Cori). Wider tests with C-AMG
(in Matlab) on AOA4 air foil and other matrices confirm the post-sweep reduces the residual
error more effectively. Results remain unchanged. Timing below:

/global/cscratch1/sd/sthomas1/g1> fgrep "solve --" nrel_5mw_g1-muelu-128-gmres-cheb-1.log
            solve --       avg: 0     min: 0     max: 0
            solve --       avg: 488.069     min: 486.7     max: 489.225
            solve --       avg: 352.963     min: 352.942     max: 352.972
/global/cscratch1/sd/sthomas1/g1> fgrep "solve --" nrel_5mw_g1-muelu-128-gmres-cheby-post-1.log
            solve --       avg: 0     min: 0     max: 0
            solve --       avg: 488.481     min: 487.096     max: 489.641
            solve --       avg: 160.619     min: 160.603     max: 160.627

2019-02-11 18:09 UTC, jhux2 commented
___
*[nrel_5mw/g1/muelu-cheby2er12-drop0.02-smoo-rebaltarg10k-explR-rebalPR-aggsize.xml, line 20 at r1](https://reviewable.io/reviews/exawind/solver-performance/4#-LYSjQOO6LGsWG94fnXa:-LYSjQOO6LGsWG94fnXb:b-gz4k7z) ([raw file](https://github.com/exawind/solver-performance/blob/e1ab2ab0a7d991df7578d3760d4f7b0ad924f5b8/nrel_5mw/g1/muelu-cheby2er12-drop0.02-smoo-rebaltarg10k-explR-rebalPR-aggsize.xml#L20)):*
> ```XML
> 
>   <Parameter        name="smoother: post type"              type="string"   value="CHEBYSHEV"/>
>   <ParameterList    name="smoother: post params">
> ```

Presmoothing is still active.  This changes the post-smoother options.  Could you please post the MueLu summary that describes the number of levels, complexity, smoothers, etc.?


<!-- Sent from Reviewable.io -->

2019-02-11 18:10 UTC, jhux2 requested changes
See my comment above.

2019-02-13 20:19 UTC, jhux2 commented
@sthomas61 I may have misread your proposed change.  The input deck is running a V(1,2) cycle, which is consistent with your comment.  Can you confirm?

2019-02-13 20:39 UTC, jhux2 commented
@sthomas61 wrote:
> correct - and increasing the eigenvalue iterations may lead to better (lower) times as well

Ok.  The file should be renamed.  I don't love this, but for example,
`muelu-cheby(2,1)-drop0.02-smoo-rebaltarg10k-explR-rebalPR-aggsize.xml`

The parentheses could cause problems.  Suggestions?

2019-02-13 20:49 UTC, sthomas61 commented
Will post the MueLu output and timeinf from log asap . The file notation works well if no bash or Linux wildcard conflicts

2019-02-14 00:12 UTC, jhux2 commented
@sthomas61 @lucbv @sayerhs  Based on today's solvers meeting, my understanding is that this set of changes is beneficial for the ABL simulation on Eagle.  So I think it would be better to create a new subdirectory specifically for ABL and put the deck there.  Thoughts?

2019-02-14 00:24 UTC, sayerhs commented
My understanding is that it also helps `g1` run on Cori. The timings Steve showed in this pull request are for the 5MW simulation. I think he is just reporting that the settings is also beneficial for the ABL simulations on NREL Eagle system, but I suspect the gains will carry over for ABL simulations on other systems also (worth checking on Cori though). Based on that I do see value in updating the 5MW settings or at least add this file with some `README` for others. 

I second the idea to create a separate ABL solver settings directory regardless of whether the 5MW settings are updated.

2019-02-14 00:30 UTC, jhux2 commented
> My understanding is that it also helps `g1` run on Cori. The timings Steve showed in this pull request are for the 5MW simulation. I think he is just reporting that the settings is also beneficial for the ABL simulations on NREL Eagle system, but I suspect the gains will carry over for ABL simulations on other systems also (worth checking on Cori though). Based on that I do see value in updating the 5MW settings or at least add this file with some `README` for others.

Yep, you are right about the timings for `g1` posted earlier in this issue.  @sthomas61 So what we captured in today's meeting minutes is not correct?

2019-02-14 18:41 UTC, jhux2 commented
@sayerhs  Here is `g1` data from the paper.  See file `thomas_etal_2017/data/cori/g1/16235403-4096core-16235403-read-restart-mom_sgs-cont_muelu-cheby2er12-drop0.02-smoo-rebaltarg10k-explR-rebalPR-aggsize-naluX-2018-11-02-cori-run1`:

```
================================
     STKPERF: Total Time: 1448.0675
     main() --   	avg: 1448.42 	min: 1447.54 	max: 1453.88
Timing for Eq: ContinuityEQS
             init --   	avg: 51.9018 	min: 49.4722 	max: 53.6593
         assemble --   	avg: 28.1572 	min: 27.8285 	max: 34.4226
    load_complete --   	avg: 8.20202 	min: 1.86748 	max: 8.38245
            solve --   	avg: 138.52 	min: 138.152 	max: 138.549
    precond setup --   	avg: 146.346 	min: 146.303 	max: 146.725
             misc --   	avg: 31.0559 	min: 30.7431 	max: 31.4828

     ContinuityEQS
     number of time steps   :         10
     number of linear solves:         20
     total linear iterations:         299
     avg linear iterations per solve: 14.9

linear solver iteration history
20  10  20  9  20  8  19  8  20  9  21  9  21  9  21  9  22  10  22  12
```

This is faster than what @sthomas61 [reported](https://github.com/Exawind/solver-performance/pull/4#issue-251683846), he's investigating.

2019-02-14 21:26 UTC, sayerhs commented
@jhux2 Thanks for clarifying this. Yes, we should understand this discrepancy before `g1` files are updated.

2019-02-15 21:29 UTC, sthomas61 commented
Reducing the set-up time may lead to more reduction for g1 - using 10 eigenvalue iterations, and 2 pre/post sweeps leads to a low time (but not yet at 1450 - will test further)
sthomas1@cori09:/global/cscratch1/sd/sthomas1/g1> ./getIterHistory.sh nrel_5mw_g1-muelu-128-gmres-cheby-prepost-2.log
================================
nrel_5mw_g1-muelu-128-gmres-cheby-prepost-2.log
================================
     STKPERF: Total Time: 1491.0903
     main() --   	avg: 1490.81 	min: 1489.99 	max: 1496.35
Timing for Eq: ContinuityEQS
             init --   	avg: 52.2557 	min: 50.0402 	max: 53.9066
         assemble --   	avg: 27.4895 	min: 27.1568 	max: 33.2616
    load_complete --   	avg: 7.76044 	min: 2.00239 	max: 8.0215
            solve --   	avg: 152.948 	min: 152.892 	max: 152.973
    precond setup --   	avg: 179.257 	min: 179.116 	max: 179.309
             misc --   	avg: 31.0607 	min: 30.733 	max: 31.4665

     ContinuityEQS
     number of time steps   :         10
     number of linear solves:         20
     total linear iterations:         314
     avg linear iterations per solve: 15.7

linear solver iteration history
29  16  20  9  20  9  20  8  20  9  20  9  21  9  21  9  21  10  22  12

2019-02-15 22:29 UTC, jhux2 commented
@sthomas61 wrote
> Reducing the set-up time may lead to more reduction for g1 - using 10 eigenvalue iterations, and 2 pre/post sweeps leads to a low time (but not yet at 1450 - will test further)
[snip]
linear solver iteration history 29 16 20 9 20 9 20 8 20 9 20 9 21 9 21 9 21 10 22 12

Any idea why the iteration history is so different?

2019-02-15 22:34 UTC, sthomas61 commented
> > linear solver iteration history 29 16 20 9 20 9 20 8 20 9 20 9 21 9 21 9 21 10 22 12
> 
> Any idea why the iteration history is so different doesn't match the paper results?

The eigenvalue estimate presumably is less accurate (fewer iterations) and this 
affects the smoother (Cheby) -

2019-02-15 23:06 UTC, jhux2 commented
Did you run the exact configuration/executable as reported in the paper data directory to see if the results are reproducible?  You may have already said this already ....

2019-02-15 23:10 UTC, sthomas61 commented
> Did you run the exact configuration/executable as reported in the paper data directory to see if the results are reproducible? You may have already said this already ....

Confirmed, these are with the paper data executable. However, ran with separate pre and post smoothers in the xml - so to be identical and run with reduced eigenvalue iterations - now using a single smoother specification.

2019-02-15 23:27 UTC, jhux2 commented
The 43 second time difference is about 3%, which is well within what I'd expect in variability on Cori.  I don't know that this is worth chasing down.

2019-02-15 23:30 UTC, sthomas61 commented
> The 43 second time difference is about 3%, which is well within what I'd expect in variability on Cori. I don't know that this is worth chasing down.

OK, will let 3 more run and then stop

2019-02-21 22:05 UTC, jhux2 commented
@sthomas61 Any updates on this?

2019-02-21 22:14 UTC, sthomas61 commented
In the end leads to no further improvements for the g1 mesh. 
It does however lead to lower times for the ABL time per time step.
Recommend no change here for g1

2019-02-21 22:40 UTC, jhux2 commented
@sthomas61 Thanks for the update.  Sound like this should then be in a new subdirectory, `input-decks/abl`.

2019-04-10 17:40 UTC, jhux2 commented
@sthomas61 I think we agreed that this PR could be closed, and that you would submit a new PR for a new ABL subdirectory.

2019-04-10 17:40 UTC, closed without merging